stages:
  - test

variables:
  COMPOSER_CACHE_DIR: "$CI_PROJECT_DIR/.composer-cache"

cache:
  key:
    files:
      - composer.lock
  paths:
    - .composer-cache/
    - vendor/

before_script:
  - composer install --no-interaction --prefer-dist

phpunit:
  stage: test
  image: php:8.5-cli
  script:
    - composer test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

phpstan:
  stage: test
  image: php:8.5-cli
  script:
    - composer analyse
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
